### ISSUE TITLE
1% renders as 100%

### ISSUE THREAD

**Issue by jetrosuni** [10quality/vue-progress-bar#1]
This is caused by a bug in computed progress value.

Current code in ``vue.progress-bar.js``:
```
progress: function()
{
    if (this.value === undefined)
        return 0;
    return this.value > 1
        ? parseFloat(this.value) / 100
        : parseFloat(this.value);
}
```

Should be:
```
progress: function()
{
    if (this.value === undefined)
        return 0;
    return this.value >= 1
        ? parseFloat(this.value) / 100
        : parseFloat(this.value);
}
```

**Comment by amostajo** [comment]
This solution breaks the idea of using percentage values like (0.2 for 20% and 1 for 100%). I will not accept the pull request, although I will be adding a property for if you wish to use percentage values or not.
